version: "3"
services:
  db:
    image: "postgres:13"
    environment:
      POSTGRES_PASSWORD: super_secret
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local