version: @project.version@
default_locale_code: en_US
locales_folder: locales
command_prefix: /

github_url: https://github.com/shimmermare/InviteRoles

author:
  name: Shimmermare
  twitter_url: https://twitter.com/shimmermare
  github_url: https://github.com/shimmermare
  website_url: https://shimmermare.com


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: super_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect